### ISSUE TITLE
Does not create tournament

### ISSUE THREAD

**Issue by nmynarcik** [Tidwell/node-challonge#1]
When creating a tournament, I get a success response back from the callback, but returns no data and no new tournament is created.

```javascript
var challonge_node = require('challonge');
var AuthDetails = require('./auth.json');

function ChallongePlugin () {
	this.challonge = challonge_node.createClient({
		apiKey: AuthDetails.challonge
	});
}

// create a tournament
ChallongePlugin.prototype.create = function(tourneyData){
	this.challonge.tournaments.create({
		tournament: {
			name: 'my name',
			url: 'my-url',
			tournamentType: 'single elimination',
		},
		callback: function(err, data){
			console.log(arguments);
			if (err) { console.log('::ERROR::',err); return; }
			console.log('::Tournament Created::',data);
		}
	});
}
```

**Comment by Tidwell** [comment]
Per the challonge doc: http://api.challonge.com/v1/documents/tournaments/create

urls can only contain letters, numbers, and underscores only

changing the url to match the requirement in your example works fine to create the tournament.  Note that challonge doesn't allow for duplicate urls, so you may have to tack on some numbers and letters to test.

Using the code you provided, I was able to get the following:

::ERROR:: { error: true,
  errors: [ 'URL can only contain letters, numbers, and underscores' ],
  statusCode: 422,
  text: { errors: [ 'URL can only contain letters, numbers, and underscores' ] } }
