### ISSUE TITLE
challonge.createClient massageProperties is tautologically true

### ISSUE THREAD

**Issue by rsxdalv** [Tidwell/node-challonge#2]
Upon definition, if it evaluates to false, it is set to be true.
When checked for, if it evaluates to false, you get to skip this feature.
Thus, the only way to get the raw property names is to modify the property manually on the return object from create client:

(createClientReturn).client.options.massageProperties = false;

Instead of checking for false, check for undefined as undefined !== false.

**Comment by Tidwell** [comment]
Fixed in master, will deploy in v1.2

**Comment by rsxdalv** [comment]
Cool!
