### ISSUE TITLE
Allow optional 'state' parameter for matches/index endpoint

### ISSUE THREAD

**Issue by HappyZombies** [Tidwell/node-challonge#29]
[Challonge Docs](http://api.challonge.com/v1/documents/matches/index)   state that if you add a 'state' parameter to the match index endpoint, you will get all the matches that are "open", "inprogress", etc. 

Currently this package will use the default and get all matches. So I have to use lodash to get matches with  the "open" state. It be nice if this was implemented !

**Comment by Tidwell** [comment]
All params in the challonge docs should already be supported.  We don't do a mapping for each individual property, we just serialize and pass the params along.  Give something like the following a try:

```js
const challonge = require('challonge');

// create a new instance of the client
const client = challonge.createClient({
  apiKey: '***yourAPIKey***',
});

//get the matches for the 'my-tournament-url' tournament in state 'open'
client.matches.index({
  id: 'my-tournament-url',
  state: 'open',
  callback: (err, data) => {
    console.log(err, data);
  }
});
```

If this doesn't work, please let me know what the error response is and I can look in more detail.

**Comment by HappyZombies** [comment]
Ah very nice. I just tested it out and it does work. Thanks for the help. I should've just attempted to use state, but when I didn't see it in the docs I was unsure. 

Thanks again!

**Comment by HappyZombies** [comment]
I actually have an unrelated question, more about the API. You seemed to be well knowledge in it and the community of challonge API seems to be no where to be found...but anyhow, my simple question is:

I want to retrieve open matches and display the name of the players for the appropriate open match.

The problem is ....that matches/index endpoint only gets me the players id....so I have to make a request to the participants/show endpoint for each players id ? Now I have to make two requests per match to the participants/show endpoint.....so I imagine a loop will work best for this since the matches are returned in an array. But say I have 30 open matches, I will be making a request to challonge API 60 times just to get their name...and then I have to worry about assuring that the callback updates appropriately...

I see that in the participants/show endpoint, I can set a parameter 'include_matches' which will get me a match on the player but that's only if I know their id.... besides, I need to display open matches, not players individually. 

Any help on _how to get a players name based on open matches_ would be appreciated. Thanks for reading.

**Comment by Tidwell** [comment]
Your best bet is going to be to call the participant list endpoint and from that make an id->name lookup table.

Then when you get the matches, you can use the map to find the users name.

Something like:

```js
const idToNameMap = {};
client.participants.index({
  id: tourneyName,
  callback: (err, data) => {
    for (var i in data) {
    	idToNameMap[data[i].participant.id] = data[i].participant.displayName;
    }
  }
});
```
