### ISSUE TITLE
Unable to update score

### ISSUE THREAD

**Issue by eaaliprantis** [Tidwell/node-challonge#3]
Hello,

So whenever I try to do an update on a match (when the event is underway/going), I am unable to update the match with the scores.  The account has admin rights to the organization and the id of the tournament is correct since i was able to retrieve the match previously.

Note: I receive no error message or data message at all.  It doesn't return anything from console either.

Please advise.

**Comment by Tidwell** [comment]
Can you link with the code you are running?  I wrote a quick tests and it seemed to run and the result showed up in challonge.

The steps:

```js
.create(); //create the tournament
.participants.create() //create player1
.participants.create() //create player2
.start() //start the event
.matches.index() //get the matches that were generated
.matches.update() //add a result for the match
```

```js
var challonge = require('node-challonge');

var client = challonge.createClient({
	apiKey: '***YOUR***KEY***',
	format: 'json',
	version: 1,
});

var tourneyName = 'mytesttournament' + Math.floor(Math.random()*10000);

client.tournaments.create({
	tournament: {
		name: 'name-'+tourneyName,
		url: tourneyName,
		signupCap: 8,
		tournamentType: 'single elimination',
	},
	callback: function(err,data){
		if (err) { console.log(err); return; }
		console.log(data);

		pcreate('player1');
	}
});

function pcreate(name) {
	client.participants.create({
		id: tourneyName,
		participant: {
			name: name
		},
		callback: function(err,data){
			if (err) { console.log(err); return; }
			console.log(data);
			if (name === 'player1') {
				pcreate('player2');
			} else {
				start();
			}
		}
	});
}

function start() {
	client.tournaments.start({
		id: tourneyName,
		callback: function(err,data){
			if (err) { console.log(err); return; }
			console.log(data);

			mindex();
		}
	});
}

function mindex() {
	client.matches.index({
		id: tourneyName,
		callback: function(err,data){
			if (err) { console.log(err); return; }

			mupdate(data[0].match.id, data[0].match.player1Id);
		}
	});
}

function mupdate(matchId, winnerId) {
	client.matches.update({
		id: tourneyName,
		matchId: matchId,
		match: {
			scoresCsv: '3-0',
			winnerId: winnerId
		},
		callback: function(err,data){
			if (err) { console.log(err); return; }
			console.log(data);
		}
	});
}
```

**Comment by eaaliprantis** [comment]
Weird.

This is what i have:

apis.challonge.challonge is the object that is similar to your client.

`let finalScore = p1_score + '-' + p2_score;
													let finalMatchId = matchId;
													if(p1_score > p2_score) {
														//score updated - - p1 wins
														console.log("P1 wins!");
														console.log("finalScore: " + finalScore + " | tourneyurl: " + tourneyurl + " | matchId: " + matchId);
														console.log("apis: " + apis.challonge.challonge.matches.update);
														apis.challonge.challonge.matches.update({
															id: tourneyurl,
															matchId: finalMatchId,
															match: {
																scoresCsv: finalScore,
																winnerId: p1_id
															},
															callback: function(err, data) {
																console.log("score updating.....");
																if(err) {
																	console.log(err);
																	return;
																} else {
																	console.log("Message deleting....");
																	/*
																	newmessage.delete();
																	console.log("Message deleted...");
																	message.reply(" your score has been updated.");
																	let embed = new Discord.RichEmbed();
																	embed.setTitle("Score update!");
																	embed.setAuthor("Robot | DJD", "https://cdn.discordapp.com/attachments/281308318360666112/283745108673953792/botlojotiny.png");
																	embed.addField("Match", match);
																	embed.addField("Player 1's (" + p1_name + ") score", p1_score);
																	embed.addField("Player 2's (" + p2_name + ") score", p2_score);
																	embed.addField("Final score", finalScore);
																	embed.addField("Winner", "Congrats " + ((p1_score > p2_score) ? p1_name : p2_name) + " on advancing to the next round.");
																	message.channel.sendEmbed(embed);
																	*/
																	return;
																}
															}
														});``

**Comment by eaaliprantis** [comment]
Like to me, looking at both codes should work.  But mine doesn't.  It doesn't even turn an error or anything, which is strange and perplexing

**Comment by eaaliprantis** [comment]
So, it works, but doesn't publish/change the score for some reason.  This is on a subdomain though.  Could that be the possible issue?  It is able to find the match, determine the winner, but it does not post the score or update it.

**Comment by Tidwell** [comment]
I'll test with your code tonight and see if I can find anything.  I dont think the subdomain effects it, but there might be an issue updating an already existing score.  I'll give it a try and see what happens.

**Comment by eaaliprantis** [comment]
Alright, thanks.  :)

**Comment by Tidwell** [comment]
I just encountered a bug where urls were not being formed correctly on subdomains with a hyphen in their name.  Perhaps this is the case?  If it is, I've got a fix that will be in the next version.

**Comment by eaaliprantis** [comment]
Well, based on the npm (challonge) that was forked/created by the other guys (as we discussed in another thread), it should work because it works for everything else but actually updating the scores.  Like it will grab the match, or index the matches for that tournament, but still no luck in getting the score to post :(

**Comment by Tidwell** [comment]
I'm almost positive this relates to the changes that were made in that npm published version.  In reviewing those changes theres a critical bug where a large number of the parameters are not being appended to the request, specifically the nested properties (like tournament[score]), as they are in a non-standard formatting for qs params. It looks like when they switched to using request instead of native https they forgot to add the non-standard params.

I'll be reverting that change for 1.2 as I do not want to use any external dependencies if they are unnecessary or (in this case) error-prone.

If you switch your dependency to use the github url master branch (that will be published to npm as v1.2 today or tomorrow) it should resolve the issue.

in package.json:
```js
{
  dependencies: {
    "challonge": "Tidwell/node-challonge"
  }
}
```

**Comment by eaaliprantis** [comment]
So, if i'm understanding this correctly, the dependency would be calling the "Tidwell/node-challonge" even though the NPM was already installed?

**Comment by eaaliprantis** [comment]
OMG @Tidwell that worked.  Reporting score/match is working great.  I'm thrilled and happy <3  If you need development, i'm down to assist with whatever you need done :)

**Comment by Tidwell** [comment]
Awesome!  I'm going to leave this issue open till 1.2 is pushed to npm.  After that you should be fine to switch back to the regular dependency name.

**Comment by Tidwell** [comment]
Version 2.0.0 has been pushed to npm.

**Comment by eaaliprantis** [comment]
Excellent :) I'm very happy of the amount of work that you have done with the version 2.0.0
