### ISSUE TITLE
Add suggested_play_order mapping

### ISSUE THREAD

**Issue by Tidwell** [Tidwell/node-challonge#5]
Per http://feedback.challonge.com/forums/44455-feature-requests/suggestions/11659590-front-end-ui-match-identifier-does-not-match-api-m

Add support for that new field.  Probably worth checking if we are missing any other properties at the same time.

**Comment by eaaliprantis** [comment]
You actually don't need to do that since when a match is returned, it is automatically in there.

**Comment by Tidwell** [comment]
awesome!
