### ISSUE TITLE
Publish 2.0.0 to npm

### ISSUE THREAD

**Issue by Tidwell** [Tidwell/node-challonge#8]
Having to clone the repo is dumb.  Needs to publish to npm.  In order to do that we need to resolve a couple issues

**Comment by eaaliprantis** [comment]
Isn't your NPM this? https://www.npmjs.com/package/challonge

**Comment by Tidwell** [comment]
Looks like someone else published it.  Thats going to be a mess to resolve.  I'll have to get in touch with whoever it was to transfer ownership.

**Comment by eaaliprantis** [comment]
Wait, could that be the reason why it might not be working? Because of that npm?

**Comment by Tidwell** [comment]
Its possible, I see a lot of changes in the challonge-js wrapper that was added.  I'm going to have to get in touch with the folks that published and have them transfer ownership/remove.

**Comment by eaaliprantis** [comment]
Yeah, the challonge-js had issues as well with reporting scores.  Yeah, a lot of people created NPMs and what not without consulting with you, which happened to me before.  I could assist with anything that you need help with.

Here is the challonge-js one: https://www.npmjs.com/package/challonge-js
And the REPO can be found here: https://github.com/jonas-vanen/node-challonge

**Comment by Tidwell** [comment]
Thanks a ton, I'll be emailing them right away and if I don't get responses will go through the standard npm support channels.  I've had to do that before with my steam api wrapper, so it should be straightforward.

**Comment by eaaliprantis** [comment]
Yeah i know.  I do like this commit that was done: https://github.com/jonas-vanen/node-challonge/commit/d98a9eb6502a215a65b319ea43f30baccf2da027

It might fix the weird issues with GET, PUT, etc.  Or it could have broke it :P

**Comment by Tidwell** [comment]
Good deal, I'm asking for a PR from challonge-js as I agree with most of the changes that are in there then removing the package so there arent two version floating around on npm.

**Comment by patresi** [comment]
Hey @Tidwell, is your npm user also Tidwell? I'll add you as the owner of https://www.npmjs.com/package/challonge I think I'm also on the collaborators list of https://www.npmjs.com/package/challonge-js so I believe I can also add you on that and then you can delete it...

**Comment by Tidwell** [comment]
Yep, thats me!
Thanks a bunch, I'll look at porting over the changes that are in challonge-js since those look like great contributions 👍

**Comment by patresi** [comment]
I've added you to both packages, glad to see you're resuming work on this! 👍

**Comment by Tidwell** [comment]
Switching to 2.0.  To resolve the merge with challonge-js and to not have to cross-compile with bable, we need to do a major version bump and change node engine to 6.0.x to allow for using es6 features, let/const/arrow functions.

**Comment by Tidwell** [comment]
Version 2.0.0 has been pushed to npm.
